"""seed

Revision ID: 5981e20d90ba
Revises: ace20197f995
Create Date: 2023-02-17 13:18:13.921442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5981e20d90ba'
down_revision = 'ace20197f995'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
