"""Init

Revision ID: ace20197f995
Revises: a4fdab8c1614
Create Date: 2023-02-17 13:11:53.059223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace20197f995'
down_revision = 'a4fdab8c1614'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
